[package]
name = "vm-zstd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstream-io = "2.2"
itertools = "0.11"
strum = "0.25"
strum_macros = "0.25"
anyhow = "1"
log = "0.4"